import React from 'react'
import './TextArea.css'

export default function TextArea({text,style}) {
    return (
        <div className='text-area'  style={{...style}} >
           sfwfjwjewbjewbfk
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam in urna tellus. Praesent ligula eros, mattis id metus ut, facilisis maximus massa. Aenean viverra placerat hendrerit. In lectus sapien, varius ac lorem non, finibus elementum turpis. Nullam vel finibus quam. In ultricies cursus molestie. Vivamus feugiat consequat varius. Curabitur faucibus odio nec tellus sollicitudin tempor. Maecenas nec imperdiet nisi. Praesent fringilla sem id augue varius, eget rutrum massa malesuada. Praesent id vulputate enim. In hac habitasse platea dictumst.

Quisque rutrum nisl non commodo egestas. Mauris ligula erat, facilisis at tristique at, aliquam vel sem. Donec lacus ligula, facilisis ac urna in, scelerisque luctus nunc. Integer et metus mi. Maecenas tortor ante, tempus at egestas eget, molestie ut tortor. Cras aliquam pulvinar leo a tempor. Donec ut efficitur arcu, non interdum augue. Phasellus ex metus, luctus in lorem vitae, lobortis aliquam ante. In augue orci, molestie et velit sed, iaculis placerat nisl.

Cras id nibh at lacus consectetur vulputate id convallis mauris. Aliquam eget faucibus turpis. Maecenas a porttitor ipsum. Donec hendrerit risus non hendrerit luctus. Nam vel ligula erat. Vivamus commodo mauris vitae metus tincidunt, nec viverra sem commodo. Proin in nibh in arcu luctus malesuada. Morbi sit amet dolor odio. Vestibulum pulvinar faucibus leo, ut scelerisque magna aliquam non. Suspendisse volutpat sed sapien id imperdiet. Integer mollis efficitur nisi ac tincidunt. Pellentesque purus odio, sodales consequat finibus ut, fringilla at felis. Aenean ac massa id eros congue finibus. Ut semper, enim in laoreet laoreet, nibh nisl vestibulum sem, id consequat tellus diam eu ante. Sed vitae neque vehicula, bibendum ex id, ornare odio. Donec iaculis tortor id nisl faucibus accumsan.

Aliquam erat volutpat. Integer fermentum ipsum enim, a varius diam molestie non. Proin quis posuere purus, non fermentum mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris nec cursus quam. Aenean ac hendrerit enim. Suspendisse luctus vestibulum dui et egestas. Vivamus eu dapibus justo. Aenean orci tellus, facilisis non lacus nec, varius volutpat ligula. Nunc ullamcorper mi a arcu condimentum, vel sodales libero molestie. Maecenas sed ipsum aliquet, gravida lorem id, tincidunt neque. Morbi ut sem eget arcu accumsan finibus. Nullam tristique tristique erat, at sodales ipsum porta et. Proin id dignissim magna. Vivamus egestas fermentum nisl, nec fringilla magna varius ut.

Nam ullamcorper turpis lacus, rhoncus bibendum sem porta non. Suspendisse potenti. In quis mollis arcu. Duis tempus nulla vitae arcu tincidunt, sed dapibus felis posuere. Vestibulum malesuada nisl at neque consequat cursus. Curabitur tristique leo nulla, ut tempor ipsum aliquam ut. Sed sed lacus rutrum, molestie diam pellentesque, fermentum nisl. Donec tempus, ligula nec blandit mollis, neque lorem tempor libero, facilisis pharetra quam tellus quis nibh. Aliquam non rutrum libero, vitae imperdiet ipsum. Suspendisse eget nibh scelerisque, auctor diam dapibus, malesuada erat.

Mauris sed ligula arcu. Donec sit amet est dapibus, pellentesque augue eget, efficitur ante. Pellentesque euismod rhoncus enim at tempor. Pellentesque elementum congue mi, commodo rhoncus erat maximus nec. Phasellus interdum sem vel ex interdum rhoncus. Phasellus accumsan molestie elit, eget dictum est tristique non. Nullam consectetur vitae metus ut porta. Nam maximus augue magna, in mollis orci tincidunt in. Proin porttitor elit ut finibus bibendum. Aenean porttitor maximus massa, ullamcorper maximus sem fringilla a. Pellentesque et justo dolor. Aenean ac nibh sit amet felis euismod porta. Quisque eget urna ultrices, pulvinar nulla et, laoreet risus. Pellentesque pulvinar quam non ligula tincidunt condimentum. Fusce vitae placerat dui.

Donec condimentum eros lectus, ut porttitor arcu luctus sed. Nullam rutrum dui at nibh aliquam, tristique mattis dui finibus. Morbi mattis mi at nisl egestas, sed feugiat est mattis. Suspendisse commodo bibendum nulla, eget sodales tortor condimentum et. Aenean elementum eros eu tortor pretium, vel sodales dui hendrerit. Nunc vulputate, elit ut hendrerit accumsan, dolor lacus hendrerit risus, et tincidunt eros mauris et lacus. Suspendisse potenti. Praesent vestibulum libero vitae auctor malesuada. Aenean a ante lobortis, aliquam risus ut, vehicula ipsum. Maecenas iaculis ornare enim, vitae euismod leo fringilla in. Morbi ornare felis sed scelerisque suscipit. Mauris convallis ante nec mauris mattis, nec varius ante mollis.

Aliquam sollicitudin elementum imperdiet. Donec ac ex sed lorem ultricies facilisis. Praesent rutrum lectus non erat porttitor, non volutpat nulla finibus. Sed ac efficitur justo. Donec eu dui eget felis viverra malesuada. Morbi velit leo, lobortis vel facilisis eu, venenatis ac felis. Phasellus facilisis euismod sagittis. Phasellus non tellus id est venenatis semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin consequat, mauris id dictum hendrerit, elit mauris lobortis erat, non pretium velit enim porta ligula. Vestibulum eget condimentum massa. Nunc mauris nisi, varius ac ultrices imperdiet, aliquet nec massa. Cras imperdiet pharetra felis in euismod. In vitae massa id dui pulvinar convallis.

In sed semper lorem. Sed sit amet laoreet lacus, id suscipit purus. Sed pharetra, magna in congue commodo, sem risus porta ante, ut rhoncus urna metus et erat. Suspendisse placerat malesuada urna. Proin elementum risus et est interdum consectetur. Curabitur rhoncus lobortis libero ut porttitor. Etiam ornare aliquet lacus, nec commodo ipsum pretium vitae. Nunc fringilla viverra enim, quis ultrices leo mollis ut. Vestibulum nec ante nec dui aliquam tincidunt. Ut cursus dapibus fermentum. Curabitur egestas, risus et fermentum ullamcorper, ex mauris interdum diam, sit amet tristique felis lorem sed dolor. Vestibulum elementum quam nec laoreet dignissim. Fusce viverra id elit ut lobortis. Fusce consequat rutrum cursus. Nam massa dolor, ornare non hendrerit suscipit, porttitor ut purus.

Vivamus dictum vulputate neque, et porta augue gravida vitae. Nullam quis lorem ac nisi feugiat commodo at eget turpis. Quisque faucibus tempus dolor, sed semper neque hendrerit id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin vel luctus eros. Quisque eget lectus sed ex malesuada aliquet. Pellentesque in porta purus, ut aliquet massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse nisl quam, condimentum sed luctus sed, faucibus tincidunt lectus. Vivamus dictum augue a quam posuere aliquam. Quisque varius odio eget est euismod, porttitor interdum dolor fringilla. Nulla at nunc nulla. Vivamus condimentum justo sit amet mauris scelerisque scelerisque. Pellentesque aliquam luctus tellus eu bibendum. Nullam eget odio ex. Nulla dignissim ultrices ex, id consectetur risus egestas sed.

Donec porttitor, mi a porttitor laoreet, nibh libero rhoncus justo, nec tempus nibh risus vitae tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sit amet risus est. Vestibulum commodo neque lacinia odio feugiat, in lacinia eros pretium. Curabitur eget magna volutpat, mollis leo id, molestie velit. Morbi sed urna et eros fermentum dignissim et at turpis. Pellentesque in ultricies lorem, non auctor nisl. Nulla pellentesque volutpat quam non maximus. Morbi pellentesque libero vel volutpat aliquet. Integer eros arcu, elementum sit amet ullamcorper sit amet, eleifend sollicitudin lacus. Duis elementum feugiat facilisis. Donec aliquet, dolor quis vestibulum viverra, ligula urna consectetur risus, sed consequat neque ipsum eu diam. Duis ultricies dolor est, sit amet gravida nibh vestibulum laoreet. Aenean tristique, nisl a fringilla elementum, metus nisi consectetur libero, et scelerisque felis mauris id nibh.

Donec eleifend fringilla accumsan. Praesent sit amet orci sed sapien porta pulvinar quis et metus. Integer vitae ante eu ligula tincidunt rutrum. Morbi ut efficitur felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec ex nibh, consequat id facilisis ut, convallis eget justo. Nullam pulvinar metus ac turpis placerat tincidunt. Fusce ut lectus lobortis, commodo felis ac, condimentum tellus. Aenean pulvinar massa lacus, a imperdiet nibh tincidunt non. Nunc maximus convallis arcu ac porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ac cursus tellus. Nunc nec interdum urna. Quisque tempus sem purus, sit amet pretium nisi elementum eu. Curabitur a diam sed tortor mollis malesuada. Nullam ac accumsan mauris, et consequat nisl.

Proin venenatis, orci vitae fringilla tristique, ligula orci convallis tellus, quis finibus odio dui quis est. Praesent pharetra dui ac vehicula iaculis. Praesent sagittis, dui id viverra eleifend, massa leo ultricies nisi, vel pulvinar leo lacus vitae purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas ac faucibus sem. Morbi sed efficitur ex. Aenean sed sollicitudin odio, sed fringilla diam. Nullam posuere, metus sit amet tincidunt sagittis, libero nisi volutpat sem, ut iaculis lectus quam a diam. Curabitur tempor pharetra enim, sed pretium libero dictum ac. Morbi ac imperdiet quam, eu elementum erat. Aenean lobortis quis lorem non consequat. Sed posuere dictum purus, in elementum purus vehicula sit amet. Praesent ullamcorper blandit elementum. Integer imperdiet nunc tellus, tristique vulputate sem vehicula ac.

Curabitur mattis interdum nunc vitae feugiat. Vivamus eget arcu magna. Proin fermentum efficitur tortor, vel sagittis felis varius eget. Donec eu posuere arcu. Quisque tincidunt lacinia quam. Morbi ornare tellus lorem, id vulputate eros bibendum quis. Nulla faucibus, neque eu maximus faucibus, leo eros interdum turpis, quis ornare sapien elit a nisi.

Sed id sodales lacus, sit amet consequat sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla fermentum nunc enim, vitae egestas lectus maximus vel. Nunc vel eros quis justo ornare mollis. Nam nisl ipsum, tristique a ligula id, pretium commodo justo. Quisque vitae venenatis neque. Etiam semper ex ac odio tempus, id iaculis lectus malesuada. Donec egestas odio eu mi convallis gravida. Etiam porta vitae mauris eu imperdiet. Fusce mauris libero, cursus eu mollis eu, facilisis ac felis. Cras iaculis pharetra neque id iaculis. Vestibulum posuere sapien ut iaculis tempus.

Phasellus at volutpat nisi, vitae tincidunt metus. Ut cursus mattis urna, eu maximus nibh bibendum quis. Donec ac fringilla magna. Nulla a risus non mauris volutpat euismod. Duis elit libero, lacinia in semper vitae, tincidunt quis nibh. Pellentesque rutrum tempor efficitur. Duis porta placerat elit id ullamcorper. Maecenas hendrerit velit blandit, iaculis dui non, sagittis lorem. Aenean eget ante ut ipsum varius imperdiet in in lectus. Sed rhoncus velit a fermentum bibendum. Integer diam sapien, euismod malesuada varius vel, imperdiet a erat. Nam lectus urna, feugiat a bibendum eget, maximus non felis. Vivamus congue, lorem at vestibulum sagittis, augue quam eleifend nisi, ut elementum lacus metus sed nisi. Nunc hendrerit sodales nunc, at condimentum massa viverra eu. Ut eleifend ex eu arcu vulputate, a pellentesque orci sodales. Etiam vehicula erat suscipit orci tincidunt porttitor.

Curabitur facilisis fermentum mauris, eget facilisis elit malesuada in. Sed ornare eros id orci bibendum lobortis. Proin et metus lectus. Integer pulvinar risus tristique, viverra nisl non, fringilla mi. Cras scelerisque orci nisl, non scelerisque lectus scelerisque vitae. Aenean velit leo, volutpat in tempus non, efficitur et risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent sed justo id mauris condimentum maximus. Vestibulum facilisis vitae justo id facilisis. Nullam ante ligula, finibus ac hendrerit quis, lacinia sed nisi. Ut mattis felis ac mi blandit viverra. Sed dictum porta vehicula. Morbi sit amet mollis augue. Phasellus elementum quis metus eget sagittis.

Ut viverra metus elit, id ultrices dolor tristique efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus aliquet dui non condimentum tristique. Etiam non sollicitudin nisl. Maecenas faucibus vel eros at vestibulum. Integer orci dui, fringilla a cursus quis, finibus quis sapien. Pellentesque sed ligula diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu rutrum elit. Fusce posuere nibh vel ex mattis tristique.

Fusce diam justo, imperdiet ut lorem ut, cursus facilisis nisl. Curabitur massa est, rhoncus a nulla id, lacinia mattis magna. Nulla lacinia nec sem quis euismod. Phasellus non nisi ut quam interdum vehicula a in odio. In commodo placerat accumsan. Nulla ornare ex eu nunc varius, quis semper mauris efficitur. Suspendisse a odio in dolor dapibus auctor eget sed lectus.

Nam sed pretium sapien. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum id ipsum id mi lacinia consequat. Aliquam tincidunt, nulla sit amet lacinia consequat, nisi neque cursus tortor, quis feugiat magna leo ac nisi. Donec suscipit elementum sollicitudin. Donec at rutrum erat. Pellentesque purus mi, interdum ac posuere sit amet, consectetur et ligula. Donec maximus lacinia facilisis. Donec vel semper augue. Fusce ac ipsum sed orci ullamcorper rhoncus. Nulla facilisi.
            
        </div>
    )
}
